apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: sw2-ml
  labels:
    app: ml-service
spec:
  type: LoadBalancer
  selector:
    app: ml-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8010
    name: http
